---
- hosts: all
  become: yes
  vars:
    zk:
      version: 3.4.11
      mirror: http://www-us.apache.org/dist
      user: zookeeper
      group: root
      install_dir: /opt
      data_dir: /opt/zookeeper/data
      log_dir: /opt/zookeeper/log
  tasks:

  - name: User | Create Group
    become_user: root
    group:
      name: "{{zk.group}}"
      state: present

  - name: User | Create User
    become_user: root
    user:
      name: "{{zk.user}}"
      group: "{{zk.group}}"
      state: present

  - name: Install add-apt-repostory
    become: yes
    apt: name=software-properties-common state=latest

  - name: Add Oracle Java Repository
    become: yes
    apt_repository: repo='ppa:webupd8team/java'

  - name: Accept Java 8 License
    become: yes
    debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

  - name: Install Oracle Java 8
    become: yes
    apt: name={{item}} state=latest
    with_items:
      - oracle-java8-installer
      - ca-certificates
      - oracle-java8-set-default

  - name: Zookeeper | Create base directory
    become_user: root
    file:
      path: "{{zk.install_dir}}"
      owner: "root"
      group: "root"
      mode: 0755
      state: directory

  - name: Zookeeper | Download
    get_url:
      url: http://www-us.apache.org/dist/zookeeper/zookeeper-{{zk.version}}/zookeeper-{{zk.version}}.tar.gz
      dest: /tmp/zookeeper-{{zk.version}}.tar.gz

  - name: Zookeeper | Extract Zookeeper
    become_user: root
    command: tar xzf /tmp/zookeeper-{{zk.version}}.tar.gz chdir="{{zk.install_dir}}"

  - name: Zookeeper | Create data directory
    become_user: root
    file:
      path: "{{zk.data_dir}}"
      owner: "{{zk.user}}"
      group: "{{zk.group}}"
      mode: 0755
      state: directory

  - name: Zookeeper | Create log directory
    become_user: root
    file:
      path: "{{zk.log_dir}}"
      owner: "{{zk.user}}"
      group: "{{zk.group}}"
      mode: 0755
      state: directory

  - name: Zookeeper | Update permissions
    become_user: root
    file:
      path: "{{ zk.install_dir }}"
      owner: "{{ zk.user }}"
      group: "{{ zk.group }}"
      recurse: yes
      mode: 0755
      state: directory

  - name: ZooKeeper | Ensure zoo.conf is present
    template:
      src: "templates/zk/zoo.cfg"
      dest: "{{zk.install_dir}}/zookeeper-{{zk.version}}/conf"

  - name: ZooKeeper | Ensure myid is set to {{cluster_node_seq}} in {{zk.data_dir}}/myid
    template:
      src: "templates/zk/myid"
      dest: "{{zk.data_dir}}"

  - name: ZooKeeper | Ensure zkEnv.sh is presnt
    template:
      src: "templates/zk/zkEnv.sh"
      dest: "{{zk.install_dir}}/zookeeper-{{zk.version}}/bin"

  - name: Zookeeper | Init as service
    template:
      src: "templates/zk/zookeeper"
      dest: "/etc/init.d/"
      mode: 0755

  - name: Zookeeper | Configure service
    file:
      src: /etc/init.d/zookeeper
      dest: /etc/rc2.d/S99zookeeper
      state: link

  - name: ZooKeeper | Service
    service:
      name: zookeeper
      enabled: yes
      state: reloaded
    ignore_errors: true

